### ISSUE TITLE
[Questions][Build] Select example does not build separately

### ISSUE THREAD

**Issue by ReBeLTheProgrammer** [palebedev/ntc-cmake#7]
I was trying to build the 'select' example separately from the repo folder.
Config:
CLion IDE, automatically detected configuration 'select' [I think, it is similar to `ninja select`].
Installed deps:
ntc-cmake (install root: ../prefix), 
boost 1.78 (install root: ../prefix/boost),
google benchmark (install root: deafult).
Compiler: clang v.11.0
CMake parameters: `-G Ninja -DCMAKE_PREFIX_PATH=../prefix`
Linux distro: Fedora, kernel v.5.10.13.

build output:
`[1/4] Building CXX object select/CMakeFiles/select.dir/src/select_reactor.cpp.o
FAILED: select/CMakeFiles/select.dir/src/select_reactor.cpp.o 
/usr/bin/clang++  -DBOOST_ALL_NO_LIB -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ASIO_NO_DYNAMIC_BUFFER_V1 -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_CONTAINER_USE_STD_EXCEPTIONS -isystem utils/include -isystem /home/therbl/CLionProjects/multithreading/prefix/boost/include -pedantic-errors -fno-math-errno -fno-signed-zeros -fno-trapping-math -Wall -Wextra -Wabstract-vbase-init -Warray-bounds-pointer-arithmetic -Wcast-align -Wclass-varargs -Wconversion -Wctor-dtor-privacy -Wdeprecated -Wdocumentation -Wdocumentation-pedantic -Wdouble-promotion -Wextra-semi -Wheader-hygiene -Wimplicit-fallthrough -Winconsistent-missing-destructor-override -Wmissing-declarations -Wmissing-prototypes -Wmissing-variable-declarations -Wnewline-eof -Wno-assume -Wno-missing-field-initializers -Wnull-dereference -Wnullable-to-nonnull-conversion -Wold-style-cast -Wover-aligned -Wpragmas -Wrange-loop-analysis -Wredundant-decls -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-field-in-constructor-modified -Wshift-sign-overflow -Wstatic-in-inline -Wthread-safety -Wundef -Wundefined-func-template -Wundefined-reinterpret-cast -Wweak-vtables -Wweak-template-vtables -Wzero-as-null-pointer-constant -fmacro-backtrace-limit=0 -ftemplate-backtrace-limit=0 -fdiagnostics-show-template-tree -std=c++2a -MD -MT select/CMakeFiles/select.dir/src/select_reactor.cpp.o -MF select/CMakeFiles/select.dir/src/select_reactor.cpp.o.d -o select/CMakeFiles/select.dir/src/select_reactor.cpp.o -c select/src/select_reactor.cpp
select/src/select_reactor.cpp:78:5: error: use of undeclared identifier 'assert'
    assert(fd>=0);
    ^
select/src/select_reactor.cpp:100:5: error: use of undeclared identifier 'assert'
    assert(fd>=0);
    ^
2 errors generated.
[2/4] Building CXX object select/CMakeFiles/select.dir/src/thread_pool.cpp.o
FAILED: select/CMakeFiles/select.dir/src/thread_pool.cpp.o 
/usr/bin/clang++  -DBOOST_ALL_NO_LIB -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ASIO_NO_DYNAMIC_BUFFER_V1 -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_CONTAINER_USE_STD_EXCEPTIONS -isystem utils/include -isystem /home/therbl/CLionProjects/multithreading/prefix/boost/include -pedantic-errors -fno-math-errno -fno-signed-zeros -fno-trapping-math -Wall -Wextra -Wabstract-vbase-init -Warray-bounds-pointer-arithmetic -Wcast-align -Wclass-varargs -Wconversion -Wctor-dtor-privacy -Wdeprecated -Wdocumentation -Wdocumentation-pedantic -Wdouble-promotion -Wextra-semi -Wheader-hygiene -Wimplicit-fallthrough -Winconsistent-missing-destructor-override -Wmissing-declarations -Wmissing-prototypes -Wmissing-variable-declarations -Wnewline-eof -Wno-assume -Wno-missing-field-initializers -Wnull-dereference -Wnullable-to-nonnull-conversion -Wold-style-cast -Wover-aligned -Wpragmas -Wrange-loop-analysis -Wredundant-decls -Wredundant-parens -Wreserved-id-macro -Wshadow-field -Wshadow-field-in-constructor-modified -Wshift-sign-overflow -Wstatic-in-inline -Wthread-safety -Wundef -Wundefined-func-template -Wundefined-reinterpret-cast -Wweak-vtables -Wweak-template-vtables -Wzero-as-null-pointer-constant -fmacro-backtrace-limit=0 -ftemplate-backtrace-limit=0 -fdiagnostics-show-template-tree -std=c++2a -MD -MT select/CMakeFiles/select.dir/src/thread_pool.cpp.o -MF select/CMakeFiles/select.dir/src/thread_pool.cpp.o.d -o select/CMakeFiles/select.dir/src/thread_pool.cpp.o -c select/src/thread_pool.cpp
select/src/thread_pool.cpp:22:55: error: no member named 'test' in 'std::atomic_flag'
                    return !tasks_.empty()||stopping_.test(std::memory_order::acquire);
                                            ~~~~~~~~~ ^
select/src/thread_pool.cpp:24:30: error: no member named 'test' in 'std::atomic_flag'
                if(stopping_.test(std::memory_order::acquire))
                   ~~~~~~~~~ ^
select/src/thread_pool.cpp:33:35: error: no member named 'test' in 'std::atomic_flag'
                }while(!stopping_.test(std::memory_order::acquire)&&task);
                        ~~~~~~~~~ ^
select/src/thread_pool.cpp:50:23: error: no member named 'test' in 'std::atomic_flag'
        if(!stopping_.test(std::memory_order::acquire)){
            ~~~~~~~~~ ^
select/src/thread_pool.cpp:72:18: error: no member named 'test' in 'std::atomic_flag'
    if(stopping_.test(std::memory_order::acquire))
       ~~~~~~~~~ ^
5 errors generated.
[3/4] Building CXX object select/CMakeFiles/select.dir/src/main.cpp.o
ninja: build stopped: subcommand failed. `

The warnings (about the assert) seem to get fixed by adding the line `#include <cassert>` to src/select_reactor.hpp file, the second one is tougher. It is in the c++20 standard, and the compiler gets -std=c++2a parameter, so i can't understand what's the problem.

**Comment by palebedev** [comment]
These problems are actually specific to cosec-examples, not ntc-cmake.

An include of `<cassert>` is missing, indeed. Those are not warnings, but hard errors.
`std::atomic_flag::test` is in C++20, but not implemented by libstdc++ yet. The workaround is to downgrade to `atomic_bool`.

Fixed both, thank you.
